#ifndef MENU_HPP_INCLUDED
#define MENU_HPP_INCLUDED

#include <iostream>

//MENU
enum{ SALIR, BURBUJA, SELECCION, INSERCION, SHELLSORT, QUICKSORT, MERGESORT};

int Menu();

#endif // MENU_HPP_INCLUDED
